force-app/main/default/objects/Quote/fields/IDInterno__c.field-meta.xml
<CustomField>
    <fullName>IDInterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Interno</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Escalonamiento__c.field-meta.xml
<CustomField>
    <fullName>Escalonamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a que partida esta relacionado el escalonamiento</description>
    <label>Escalonamiento</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Partidas de presupuesto</relationshipLabel>
    <relationshipName>PartidasPresupuesto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IDInterno__c.field-meta.xml
<CustomField>
    <fullName>IDInterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Interno</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/OpenContract.cls
public class OpenContract {
    
    @AuraEnabled 
    public static QuoteLineItem  getQuoteItemId(String idOportunidad){
       Quote cotizacion= [SELECT ID  FROM Quote WHERE OpportunityId=:idOportunidad and IsSyncing=true LIMIT 1  ];
       QuoteLineItem Cotizaciones=[SELECT Id,Product2.ProductCode,Product2.IDInterno__c,Quote.Opportunity.StageName   FROM QuoteLineItem WHERE QuoteId=:cotizacion.id and Escalonamiento__c=null LIMIT 1];         
       return Cotizaciones;
    }

}