force-app/main/default/objects/Opportunity/fields/CantidadTarjetas__c.field-meta.xml
<CustomField>
    <fullName>CantidadTarjetas__c</fullName>
    <label>Cantidad de tarjetas total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CantidadTarjetas__c.field-meta.xml
<CustomField>
    <fullName>CantidadTarjetas__c</fullName>
    <label>Cantidad de tarjetas o chequeras</label>
    <summarizedField>QuoteLineItem.CantidadTarjetas__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CantidadTarjetas__c.field-meta.xml
<CustomField>
    <fullName>CantidadTarjetas__c</fullName>
    <label>Cantidad de tarjetas o chequeras</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NotificarModificacionImplementacion_TEST.cls
@isTest
public class NotificarModificacionImplementacion_TEST {
	@isTest(SeeAllData=true)
    public static void metodo1(){
        Opportunity opp=[Select Id from Opportunity where StageName='Implementación' limit 1];
        /*Account acc=new Account();
        acc.Name='test';
        insert acc;              
        
        Opportunity opp=new Opportunity();
        opp.AccountId=acc.Id;
        opp.Name='test';
        opp.CloseDate=Date.today();
        opp.StageName='Cotización';
        insert opp;
        
        Quote q=new Quote();
        q.OpportunityId=opp.Id;
        q.Name='test';
        insert q;
        
        QuoteLineItem qli=new QuoteLineItem();
        qli.CantidadTarjetas__c=2;
        qli.QuoteId=q.Id;
        insert qli;
        
        WorkOrder wo=new WorkOrder();
        wo.Oportunidad__c=opp.Id;
        insert wo;*/
        List<Opportunity> lo=new List<Opportunity>{opp};
        NotificarModificacionImplementacion.notificarCambio(lo);
    }
}