force-app/main/default/objects/Opportunity/fields/CodigoClienteAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoClienteAS400__c</fullName>
    <description>Código de cliente con producto en la oportunidad</description>
    <label>Código AS400/Id. OPAM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaReasignacion__c.field-meta.xml
<CustomField>
    <fullName>FechaReasignacion__c</fullName>
    <label>Fecha de Reasignación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaUltimaActividad__c.field-meta.xml
<CustomField>
    <fullName>FechaUltimaActividad__c</fullName>
    <label>Fecha ultima actividad</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroReasignacion__c.field-meta.xml
<CustomField>
    <fullName>NumeroReasignacion__c</fullName>
    <label>Número de Reasignación</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SemaforosSchedule.cls
global class SemaforosSchedule implements Schedulable {
   global void execute(SchedulableContext sc) {
       //String queryFL='Select Id,FechaUltimaActividad__c,NumeroReasignacion__c,FechaReasignacion__c from Lead where FechaReasignacion__c!=null and NumeroReasignacion__c=1';
       String queryDL='Select Id,FechaUltimaActividad__c,NumeroReasignacion__c,FechaReasignacion__c,Owner.UserRole.Name,OwnerId from Lead where FechaReasignacion__c!=null and NumeroReasignacion__c>=10 and NumeroReasignacion__c<=13 and IsConverted=false and CountryCode!=\'PE\' and CountryCode!=\'CO\' and Status!=\'Calificado\' and Status!=\'No interesado\' and Status!=\'Descartado\'';
       //String queryFO='Select Id,FechaUltimaActividad__c,NumeroReasignacion__c,FechaReasignacion__c,CloseDate,StageName,Account.CodigoClienteAS400__c,AccountId from Opportunity where FechaReasignacion__c!=null and NumeroReasignacion__c=1';
       String queryDO='Select Id,FechaUltimaActividad__c,NumeroReasignacion__c,FechaReasignacion__c,CloseDate,StageName,Account.CodigoClienteAS400__c,AccountId,Owner.UserRole.Name,OwnerId from Opportunity where FechaReasignacion__c!=null and ((NumeroReasignacion__c>=10 and NumeroReasignacion__c<=13) or (NumeroReasignacion__c>=20 and NumeroReasignacion__c<=22)) and (StageName=\'Cotización\' or StageName=\'Contrato\')';
       /*BatchSemaforosLead semFieldLead = new BatchSemaforosLead(queryFL,'FIELD'); 
       Database.executebatch(semFieldLead);*/
       
       BatchSemaforosLead semDistantLead = new BatchSemaforosLead(queryDL,'DISTANT'); 
       Database.executebatch(semDistantLead,200);
       
       /*BatchSemaforosOportunidad semFieldOpp = new BatchSemaforosOportunidad(queryFO,'FIELD'); 
       Database.executebatch(semFieldOpp,200);*/
       
       BatchSemaforosOportunidad semDistantOpp = new BatchSemaforosOportunidad(queryDO,'DISTANT'); 
       Database.executebatch(semDistantOpp,200);
   }
}