force-app/main/default/objects/Opportunity/fields/Facturacion1__c.field-meta.xml
<CustomField>
    <fullName>Facturacion1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturación 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Facturación 1)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Facturacion2__c.field-meta.xml
<CustomField>
    <fullName>Facturacion2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facturación 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Facturación 2)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Familia__c.field-meta.xml
<CustomField>
    <fullName>Familia__c</fullName>
    <label>Soluciones</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ayuda Social</fullName>
            </value>
            <value>
                <fullName>Combustible</fullName>
            </value>
            <value>
                <fullName>Despensa</fullName>
            </value>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Vestimenta</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Ticket Car</fullName>
            </value>
            <value>
                <fullName>Regalo</fullName>
            </value>
            <value>
                <fullName>Empresarial</fullName>
            </value>
            <value>
                <fullName>Ticket Restaurante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pedidos__c.field-meta.xml
<CustomField>
    <fullName>Pedidos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedidos</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Pedidos)</relationshipLabel>
    <relationshipName>Oportunidades3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RecursosHumanos__c.field-meta.xml
<CustomField>
    <fullName>RecursosHumanos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recursos humanos</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Recursos humanos)</relationshipLabel>
    <relationshipName>Oportunidades4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RegistroPatronal__c.field-meta.xml
<CustomField>
    <fullName>RegistroPatronal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Registro Patronal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PantallaIntermediaContratoControllerTest.cls
@isTest 
private class PantallaIntermediaContratoControllerTest {
	@isTest 
    static void myUnitTest(){
        

            Account cta = new Account(Name='cuenta', NumberOfEmployees = 12, NumeroEmpleados__c = '1-25');
            insert cta;
            Opportunity opp = new Opportunity(Name = 'test', StageName = 'test', CloseDate=date.today(),Familia__c = 'familiaTest', AccountId=cta.Id );
            insert opp;
        	Contact contacto = new Contact(LastName='ksdas',AccountId=cta.Id, Email = 'test@mail.com');
        	insert contacto;
		
            
            Test.setCurrentPageReference(new PageReference('Page.myPage'));
			System.currentPageReference().getParameters().put('id', opp.Id);
			System.currentPageReference().getParameters().put('indice', '1');
            apexPages.StandardController std = new apexPages.StandardController(opp);
            PantallaIntermediaContratoController convertir = new PantallaIntermediaContratoController(std);
        	//convertir.guardar();
    }
    
	@isTest 
    static void myUnitTestDos(){
        

            Account cta = new Account(Name='cuenta',RegistroPatronal__c='dsadsa',SucursalFacturacion__c='dsa', NumberOfEmployees = 12, NumeroEmpleados__c = '1-25');
            insert cta;
            Opportunity opp = new Opportunity(Name = 'test', StageName = 'test', CloseDate=date.today(),Familia__c = 'familiaTest', AccountId=cta.Id );
            insert opp;
        	Contact contacto = new Contact( LastName='ksdas',AccountId=cta.Id, Email = 'test@mail.com');
        	insert contacto; 
		 
            opp.Facturacion1__c=contacto.Id;
            opp.Facturacion2__c=contacto.Id;
            opp.Pedidos__c=contacto.Id;
            opp.RecursosHumanos__c=contacto.Id;
        	upsert opp;
            Test.setCurrentPageReference(new PageReference('Page.myPage'));
			System.currentPageReference().getParameters().put('id', opp.Id);
			System.currentPageReference().getParameters().put('indice', '1');
            apexPages.StandardController std = new apexPages.StandardController(opp);
            PantallaIntermediaContratoController convertir = new PantallaIntermediaContratoController(std);
        	//convertir.guardar();
    }
}