force-app/main/default/objects/Opportunity/fields/Familia__c.field-meta.xml
<CustomField>
    <fullName>Familia__c</fullName>
    <label>Soluciones</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ayuda Social</fullName>
            </value>
            <value>
                <fullName>Combustible</fullName>
            </value>
            <value>
                <fullName>Despensa</fullName>
            </value>
            <value>
                <fullName>Mantenimiento</fullName>
            </value>
            <value>
                <fullName>Vestimenta</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Ticket Car</fullName>
            </value>
            <value>
                <fullName>Regalo</fullName>
            </value>
            <value>
                <fullName>Empresarial</fullName>
            </value>
            <value>
                <fullName>Ticket Restaurante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerarContratoControllerTest.cls
@isTest
private class GenerarContratoControllerTest {
    @isTest 
    static void myUnitTest(){
        
            Account cta = new Account(Name='cuenta', NumberOfEmployees = 12, NumeroEmpleados__c = '1-25');
            insert cta;
            Opportunity opp = new Opportunity(Name = 'test', StageName = 'test', CloseDate=date.today(),Familia__c = 'familiaTest', Account=cta );
            insert opp;
            Test.setCurrentPageReference(new PageReference('Page.myPage'));
			System.currentPageReference().getParameters().put('id', opp.Id);
            apexPages.StandardController std = new apexPages.StandardController(opp);
            GenerarContratoController convertir = new GenerarContratoController(std);
    }
    @isTest 
    static void dos(){
        
            Account cta = new Account(Name='cuenta', NumberOfEmployees = 12, NumeroEmpleados__c = '1-25');
            insert cta;
            Opportunity opp = new Opportunity(Name = 'test', StageName = 'test', CloseDate=date.today(),Familia__c = 'familiaTest', Account=cta );
            
            Test.setCurrentPageReference(new PageReference('Page.myPage'));
			System.currentPageReference().getParameters().put('id', opp.Id);
            apexPages.StandardController std = new apexPages.StandardController(opp);
            GenerarContratoController convertir = new GenerarContratoController(std);
    }

}