force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/Entidad_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Legal</label>
    <referenceTo>EntidadCuenta__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(AND(isActive__c, ISPICKVAL(Frecuency__c, &quot;&quot;)) ,&quot;Nuevo&quot;,IF(AND(isActive__c,NOT( ISPICKVAL(Frecuency__c, &quot;&quot;))), &quot;Activo&quot;, &quot;Inactivo&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estatus</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_UpdateAccountEstatusTest.cls
@isTest
public class Batch_UpdateAccountEstatusTest {
	@testSetup static void setup() {
		List<Account> accountList = new List<Account>();
        Account acc = new Account();
        acc.Name = 'ABCTest';
        accountList.add(acc);

        for (Integer i = 0; i < 199; i++) {
        	Account acco = new Account();
        	acco.Name = 'ABCTest'+i;   
            accountList.add(acco);
        }
        insert accountList;
        
        EntidadLegal__c entidadLegal = new EntidadLegal__c();
        entidadLegal.Name = 'HIJD93061278A';
        entidadLegal.Cuenta__c = acc.Id;
        insert entidadLegal;
        
        EntidadCuenta__c ec = [SELECT Id FROM EntidadCuenta__c WHERE Cuenta__c =: acc.Id AND EntidadLegal__c =: entidadLegal.Id limit 1];
        
        Product2 prod = new Product2();
        prod.Name = 'Producto Test';
        prod.Family = 'Vestimenta';
        prod.ProductCode = '1';
        insert prod;
        
        ContratoFilial__c contratoFilial = new ContratoFilial__c();
        contratoFilial.Name = '11-22-33333-444';
        contratoFilial.Entidad_Cuenta__c = ec.Id;
        contratoFilial.Producto__c = prod.Id;
        insert contratoFilial;
    }
   
    static testMethod void testBatch(){
        Account acc = [SELECT Id, Status__c FROM Account WHERE Name = 'ABCTest'];
        acc.Status__c = '';
        update acc;
        Test.startTest();
        	Batch_UpdateAccountEstatus batchAccount = new Batch_UpdateAccountEstatus(); 
        	Id batchId = Database.executeBatch(batchAccount, 200);
        Test.stopTest();
        acc = [SELECT Id, Status__c FROM Account WHERE Name = 'ABCTest'];
		System.assertEquals('Activo', acc.Status__c, 'correcto.');
    }
}