force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/Amount_last_order__c.field-meta.xml
<CustomField>
    <fullName>Amount_last_order__c</fullName>
    <label>Monto del ultimo pedido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <externalId>true</externalId>
    <label>Codigo AS400</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Entidad_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Legal</label>
    <referenceTo>EntidadCuenta__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field to locate accounts with no movement in their billing for the last 12 months.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Last_order_date__c.field-meta.xml
<CustomField>
    <fullName>Last_order_date__c</fullName>
    <label>Fecha de último pedido</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchContratosFiliales_TEST.cls
@isTest
public with sharing class BatchContratosFiliales_TEST {
    @TestSetup
    static void makeData(){
        Account acc = new Account();
        acc.Name = 'ABCTest';
        insert acc;
        
        EntidadLegal__c entidadLegal = new EntidadLegal__c();
        entidadLegal.Name = 'HIJD93061278A';
        entidadLegal.Cuenta__c = acc.Id;
        insert entidadLegal;
        
        EntidadCuenta__c ec = [SELECT Id FROM EntidadCuenta__c WHERE Cuenta__c =: acc.Id AND EntidadLegal__c =: entidadLegal.Id limit 1];
        
        Product2 prod = new Product2();
        prod.Name = 'Producto Test';
        prod.Family = 'Ticket Restaurante';
        prod.ProductCode = '1';
        insert prod;
        
        Date oldDate  = date.newinstance(Date.today().year()-2, Date.today().month(), 1);
        Date dateEnd = date.newinstance(Date.today().year(), Date.today().month(), 1);
        dateEnd = dateEnd.addDays(-1);
        
        ContratoFilial__c contratoInactivo = new ContratoFilial__c(Name='01-30-42424-121',CodigoAS400__c='01-30-42424-333',Amount_last_order__c = 0.00,Last_order_date__c = oldDate,isActive__c = true,Entidad_Cuenta__c = ec.Id,Producto__c = prod.Id);
        insert contratoInactivo;
        ContratoFilial__c contratoActivo = new ContratoFilial__c(Name='01-30-42424-323',CodigoAS400__c='01-30-42424-321',Amount_last_order__c = 5000.00,Last_order_date__c = dateEnd,isActive__c = true,Entidad_Cuenta__c = ec.Id,Producto__c = prod.Id);
        insert contratoActivo;
    }
    @IsTest
    static void testActiveContracts(){
        
        Test.startTest();
        Database.executeBatch(new BatchContratosFiliales(),200); 
        Test.stopTest();
        ContratoFilial__c contratosActivos = [SELECT Id,isActive__c,Amount_last_order__c,Last_order_date__c  FROM ContratoFilial__c WHERE CodigoAS400__c = '01-30-42424-321' limit 1];
        System.assertEquals(true, contratosActivos.isActive__c);
    }
    @IsTest
    static void testInactiveContracts(){
        
        Test.startTest();
        Database.executeBatch(new BatchContratosFiliales(),200); 
        Test.stopTest();
        ContratoFilial__c contratosActivos = [SELECT Id,isActive__c,Amount_last_order__c,Last_order_date__c  FROM ContratoFilial__c WHERE CodigoAS400__c = '01-30-42424-333' limit 1];
        System.assertEquals(false, contratosActivos.isActive__c);
    }
}