force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <externalId>true</externalId>
    <label>Codigo AS400</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerContratoFilialHandler_TEST.cls
@isTest
public class TriggerContratoFilialHandler_TEST {
    @isTest
    public static void metodo1(){
        insert new ContratoFilial__c(Name='01-32-53666-002',CodigoAS400__c='01-32-53666-002');
        
        ContratoFilial__c cf = new ContratoFilial__c(Name='01-32-53644-002',CodigoAS400__c='01-32-53644-002');
        insert cf; 
        
        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true, ProductCode = '222', SendToSIGLO__c = true, IDInterno__c = '29');
        insert prod;
        
        cf.Producto__c = prod.Id;
        update cf;
        
        
    }	
}