force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/Entidad_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Legal</label>
    <referenceTo>EntidadCuenta__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field to locate accounts with no movement in their billing for the last 12 months.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Vista_EjecutivosAsignadosController_Test.cls
@isTest
public class Vista_EjecutivosAsignadosController_Test {
     @isTest(seeAllData=true)
     public static void Test(){
         
         ContratoFilial__c cf = [Select Entidad_Cuenta__r.Cuenta__r.Id
                                 From ContratoFilial__c Where isActive__c=true LIMIT 1];
         
        Vista_EjecutivosAsignadosController.getListEjecutivos(cf.Entidad_Cuenta__r.Cuenta__r.Id);
    }
    

    @isTest
    public static void accountWithoutContract() {
              
        Account acc=new Account();
        acc.Name='test';
        insert acc;
        Contact c=new Contact();
        c.AccountId=acc.Id;
        c.FirstName='test';
        c.LastName='test';
        insert c;
        
        
        Vista_EjecutivosAsignadosController.getListEjecutivos(acc.Id);
    }
    
    

    
}