force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <externalId>true</externalId>
    <label>Codigo AS400</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_operations_alert__c.field-meta.xml
<CustomField>
    <fullName>Client_operations_alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca para alertar cuando no ha habido operaciones de cliente en los últimos n meses (configurable).</description>
    <label>Alerta por operaciones cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CodigoClienteAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoClienteAS400__c</fullName>
    <description>Código de cliente con producto en la oportunidad</description>
    <label>Código AS400/Id. OPAM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Administrador de Plataforma</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Contacto)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contrato_Filial__c.field-meta.xml
<CustomField>
    <fullName>Contrato_Filial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SubCuenta</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>La cuenta de la oportunidad no coincide con la de la sub cuenta</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>ContratoFilial__c.Entidad_Cuenta__r.Cuenta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ContratoFilial__c</referenceTo>
    <relationshipLabel>Filial_Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Follow_up_alert__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca para alertar cuando no ha habido seguimiento en los últimos n meses (configurable).</description>
    <label>Alerta por seguimiento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityClosing_Test.cls
@isTest
private class OpportunityClosing_Test{
    @isTest static void test_method_one(){
        Opportunity_closing__c cs = new Opportunity_closing__c();
        cs.No_follow_up_alert__c = 5;
        cs.No_follow_up_closing__c = 6;
        cs.No_client_operations_alert__c = 12;
        cs.No_client_operations_closing__c = 13;
        insert cs;
        
        Account a = new Account(
            Name = 'cuenta'
        );
        insert a;
        
        Contact c = new Contact(
            AccountId = a.Id,
            FirstName = 'Nombre',
            LastName = 'Apellido'
        );
        insert c;
        
        Opportunity opp1 = new Opportunity(
            AccountId = a.Id,
            Name = 'test Seguimiento',
            StageName = 'Cotización',
            CloseDate = system.today().addmonths(1),
            Contacto__c = c.Id
        );
        insert opp1;
        
        ContratoFilial__c cf = new ContratoFilial__c(
            Name = '01-01-00001-999',
            CodigoAS400__c = '01-01-00001-999'
        );
        insert cf;
        
        Opportunity opp2 = new Opportunity(
            AccountId = a.Id,
            Contrato_Filial__c = cf.Id,
            CodigoClienteAS400__c = '01-01-00001-999',
            Name = 'test Operaciones',
            StageName = 'Cotización',
            CloseDate = system.today().addmonths(1),
            Contacto__c = c.Id
        );
        insert opp2;
        
        Opportunity opp3 = new Opportunity(
            AccountId = a.Id,
            Name = 'test Seguimiento',
            StageName = 'Cotización',
            CloseDate = system.today().addmonths(1),
            Contacto__c = c.Id,
            Follow_up_alert__c = true
        );
        insert opp3;
        
        Opportunity opp4 = new Opportunity(
            AccountId = a.Id,
            Contrato_Filial__c = cf.Id,
            CodigoClienteAS400__c = '01-01-00001-999',
            Name = 'test Operaciones',
            StageName = 'Cotización',
            CloseDate = system.today().addmonths(1),
            Contacto__c = c.Id,
            Client_operations_alert__c = true
        );
        insert opp4;
        
        OpportunityClosing.FollowUpAlert();
        OpportunityClosing.FollowUpClosing();
        OpportunityClosing.ClientOperationsAlert();
        OpportunityClosing.ClientOperationsClosing();
    }
}