force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/Amount_last_order__c.field-meta.xml
<CustomField>
    <fullName>Amount_last_order__c</fullName>
    <label>Monto del ultimo pedido</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Entidad_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Legal</label>
    <referenceTo>EntidadCuenta__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field to locate accounts with no movement in their billing for the last 12 months.</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Last_order_date__c.field-meta.xml
<CustomField>
    <fullName>Last_order_date__c</fullName>
    <label>Fecha de último pedido</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchContratosFiliales.cls
global with sharing class BatchContratosFiliales Implements Database.Batchable<sObject>, Database.Stateful{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Database.QueryLocator resultados=  Database.getQueryLocator('SELECT Id,isActive__c,Amount_last_order__c,Last_order_date__c,Entidad_Cuenta__c  FROM ContratoFilial__c Order By Entidad_Cuenta__c,CreatedDate DESC');
        return resultados;
    }
    global void execute(Database.BatchableContext BC, List<sObject> contratos){ 
        
        List<ContratoFilial__c> contratosFilial = (List<ContratoFilial__c>) contratos;
        List<ContratoFilial__c> contratosActualizados =  new List<ContratoFilial__c>();
        Map<Id,ContratoFilial__c> mapContratos = new Map<Id,ContratoFilial__c>();
        
        Date dateEnd = date.newinstance(Date.today().year(), Date.today().month(), 1);
        dateEnd = dateEnd.addDays(-1);
        Date dateIni= dateEnd.addMonths(-12);
        for(ContratoFilial__c con : contratosFilial) {
            if(con.Last_order_date__c >=  dateIni && con.Last_order_date__c <= dateEnd && con.Amount_last_order__c > 0){
                con.isActive__c = true;
            } else {
                con.isActive__c = false;
            }
            contratosActualizados.add(con);
        }
        mapContratos.putall(contratosActualizados);
        Database.update(mapContratos.values(),false);
    }

    global void finish(Database.BatchableContext Bc) {

    }
    
}