force-app/main/default/objects/Contrato2__c/Contrato2__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite el guardado de los contratos por ADV</description>
    <label>Administración de Venta</label>
    <nameField>
        <label>Nombre de Contrato 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Administración de Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato2__c/fields/Dias_credito__c.field-meta.xml
<CustomField>
    <fullName>Dias_credito__c</fullName>
    <label>Días de crédito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Garantia_Negociando__c.field-meta.xml
<CustomField>
    <fullName>Garantia_Negociando__c</fullName>
    <label>¿Qué Garantía Estoy Negociando?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Linea_Operativa__c.field-meta.xml
<CustomField>
    <fullName>Linea_Operativa__c</fullName>
    <label>Línea Operativa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partida de presupuesto</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Contratos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Periodo_Liberacion__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Liberacion__c</fullName>
    <label>Periodo de Liberación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Quincenal</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Porcentaje_Comision__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_Comision__c</fullName>
    <label>% Comisión</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CodigoClienteAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoClienteAS400__c</fullName>
    <description>Código de cliente con producto en la oportunidad</description>
    <label>Código AS400/Id. OPAM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contrato2__c.field-meta.xml
<CustomField>
    <fullName>Contrato2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato Asociado</label>
    <referenceTo>Contrato2__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsApprovedCreditEval__c.field-meta.xml
<CustomField>
    <fullName>IsApprovedCreditEval__c</fullName>
    <label>Tiene Aprobado Evaluación Crédito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>En Proceso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Producto_cotizacion__c.field-meta.xml
<CustomField>
    <fullName>Producto_cotizacion__c</fullName>
    <label>Producto cotización</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PartidaPresupuesto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreditEvaluation.cls
public class CreditEvaluation {
/*
     @AuraEnabled
    public static Map<String,String> getDatos(string idOportunidad){
        Map<String,string> res=new Map<String,string>();
        FOR (Opportunity opp : [SELECT Account.Name, Producto_cotizacion__c, Account.CodigoClienteAS400__c, Account.Sector__c, IsApprovedCreditEval__c FROM Opportunity WHERE Id =: idOportunidad]){
        	res.put('NombreCliente',opp.Account.Name);
            res.put('Producto',opp.Producto_cotizacion__c);
            res.put('NumCliente',opp.Account.CodigoClienteAS400__c);
            res.put('Sector',opp.Account.Sector__c);
             res.put('ProcesoAprobacion',opp.IsApprovedCreditEval__c);
        }
        
        FOR (Contrato2__c contrato : [SELECT Id, Periodo_Liberacion__c, Linea_Operativa__c, Dias_credito__c, Porcentaje_Comision__c, Garantia_Negociando__c FROM Contrato2__c WHERE PartidaPresupuesto__r.Quote.Opportunity.Id =:  idOportunidad LIMIT 1]){
           res.put('LineaOperativa',contrato.Linea_Operativa__c);
            res.put('FrecuenciaFacturacion',contrato.Periodo_Liberacion__c);
            res.put('DiasCredito',string.valueOf(contrato.Dias_credito__c));
            res.put('PorcComision',string.valueOf(contrato.Porcentaje_Comision__c));
            res.put('GarantiaNegociando',string.valueOf(contrato.Garantia_Negociando__c));
        }
        
        return res;
    }
   
    @AuraEnabled
    public static void GuardarDatos(string idOportunidad, string periodoLiberacion, decimal lineaOperativa, decimal diasCredito, decimal PorcComision, string garantiaNegociando, boolean Aprobar){
        Contrato2__c contrato = [SELECT Id FROM Contrato2__c WHERE PartidaPresupuesto__r.Quote.Opportunity.Id =:  idOportunidad LIMIT 1];
        
        if (contrato != null){
        	contrato.Periodo_Liberacion__c = periodoLiberacion;
            contrato.Linea_Operativa__c = string.valueOf(lineaOperativa);
            contrato.Dias_credito__c = diasCredito;
            contrato.Porcentaje_Comision__c = PorcComision;
            contrato.Garantia_Negociando__c = garantiaNegociando;
            update contrato;
        }
        
        if (Aprobar){
            Opportunity Opp = [SELECT 	IsApprovedCreditEval__c FROM Opportunity Where Id =: idOportunidad];
            Opp.IsApprovedCreditEval__c = 'En Proceso';
            update Opp;
        }
        
    }
    
    @AuraEnabled
    public static List<ContentDocumentLink> getOppAttachments(Id oppId) {
		List<ContentDocumentLink> oppAttachments = [SELECT ContentDocumentId, ContentDocument.Title, ContentDocument.LatestPublishedVersionId FROM ContentDocumentLink WHERE LinkedEntityId = :oppId];		
        return oppAttachments;
	}
    
    @AuraEnabled
	public static Object updateDocAndOpp(Id documentId, String newTitle, Id oppId, String oppFieldName) {
		ContentDocument doc = [SELECT Id, Title FROM ContentDocument WHERE Id = :documentId];
		doc.Title = newTitle;
		Database.SaveResult updateResult = Database.update(doc);
		Map<String, Object> mapUpdateResult = new Map<String, Object>();
		mapUpdateResult.put('errors', updateResult.getErrors());
		mapUpdateResult.put('id', updateResult.getId());
		mapUpdateResult.put('isSuccess', updateResult.isSuccess());
		return mapUpdateResult;
	}
    
    @AuraEnabled
	public static Object deleteDocUpdateOpp(Id oldDocId, Id oppId) {
		Database.DeleteResult deleteResult = Database.delete(oldDocId);
		Map<String, Object> mapDeleteResult = new Map<String, Object>();
		mapDeleteResult.put('errors', deleteResult.getErrors());
		mapDeleteResult.put('id', deleteResult.getId());
		mapDeleteResult.put('isSuccess', deleteResult.isSuccess());
		return mapDeleteResult;
	}*/
}