force-app/main/default/objects/Contrato2__c/Contrato2__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite el guardado de los contratos por ADV</description>
    <label>Administración de Venta</label>
    <nameField>
        <label>Nombre de Contrato 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Administración de Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato2__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <label>Código AS400/Id. OPAM</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partida de presupuesto</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Contratos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <externalId>true</externalId>
    <label>Codigo AS400</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Contrato_2__c.field-meta.xml
<CustomField>
    <fullName>Contrato_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato2__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_operations_alert__c.field-meta.xml
<CustomField>
    <fullName>Client_operations_alert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca para alertar cuando no ha habido operaciones de cliente en los últimos n meses (configurable).</description>
    <label>Alerta por operaciones cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Client_operations_closing__c.field-meta.xml
<CustomField>
    <fullName>Client_operations_closing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Se marca para cerrar la oportunidad cuando no ha habido operaciones de cliente en los últimos n meses (configurable).</description>
    <label>Cierre por operaciones cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CodigoClienteAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoClienteAS400__c</fullName>
    <description>Código de cliente con producto en la oportunidad</description>
    <label>Código AS400/Id. OPAM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Incremento.recordType-meta.xml
<RecordType>
    <fullName>Incremento</fullName>
    <active>true</active>
    <businessProcess>Posventa</businessProcess>
    <label>Upselling (Incremento)</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Migracion.recordType-meta.xml
<RecordType>
    <fullName>Migracion</fullName>
    <active>true</active>
    <businessProcess>Ventas</businessProcess>
    <label>Migración</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/VentaNueva.recordType-meta.xml
<RecordType>
    <fullName>VentaNueva</fullName>
    <active>true</active>
    <businessProcess>Ventas</businessProcess>
    <label>Venta nueva</label>
</RecordType>

force-app/main/default/classes/OC_ClientOperationsClosing_Batch.cls
global class OC_ClientOperationsClosing_Batch implements Database.Batchable<sObject>{
    global final Date fecha;
    
    global OC_ClientOperationsClosing_Batch(){
        Opportunity_closing__c co = Opportunity_closing__c.getOrgDefaults();
        this.fecha = system.today().addmonths(-integer.ValueOf(co.No_client_operations_closing__c));
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([
            Select Id, Name, CodigoClienteAS400__c
              From Opportunity
             where RecordType.DeveloperName in ('VentaNueva', 'Migracion', 'Incremento')
               and IsClosed = false
               and CodigoClienteAS400__c != null
               and Client_operations_alert__c = true
               and Client_operations_closing__c = false
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Opportunity> scope){
        Pattern p = Pattern.compile('^[0-9]{2}[-]{1}[0-9]{2}[-]{1}[0-9]{5}[-]{1}[0-9]{3}$');
        
        Set<Id> sos = new Set<Id>();
        for(Opportunity op : scope){
            Matcher m = p.matcher(op.CodigoClienteAS400__c);
            if(m.matches()){
                sos.add(op.Id);
            }
        }
        
        List<ContratoFilial__c> lcfs = [
            Select Id, CodigoAS400__c, Contrato_2__r.PartidaPresupuesto__r.Quote.OpportunityId, CreatedDate,
                   (Select Id from Facturaciones_Mensuales__r),
                   (Select Id from Informacion_de_Pedidos__r)
              From ContratoFilial__c
             where Contrato_2__r.PartidaPresupuesto__r.Quote.OpportunityId in: sos
               and CreatedDate <: this.fecha
        ];
        
        Map<Id, ContratoFilial__c> mcfs = new Map<Id, ContratoFilial__c>();
        for(ContratoFilial__c cf : lcfs){
            mcfs.put(cf.Contrato_2__r.PartidaPresupuesto__r.Quote.OpportunityId, cf);
        }
        
        List<Opportunity> uopps = new List<Opportunity>();
        for(Opportunity op : scope){
            if(mcfs.containsKey(op.Id)){
                ContratoFilial__c cf = mcfs.get(op.Id);
                if(cf.Facturaciones_Mensuales__r == null || cf.Facturaciones_Mensuales__r.size() == 0){
                    if(cf.Informacion_de_Pedidos__r == null || cf.Informacion_de_Pedidos__r.size() == 0){
                        op.Client_operations_closing__c = true;
                        uopps.add(op);
                    }
                }
            }
        }
        system.debug('uopps: ' + uopps);
        database.update(uopps, false);
    }
    
    global void finish(Database.BatchableContext BC){
    }
}