force-app/main/default/objects/Contrato2__c/Contrato2__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite el guardado de los contratos por ADV</description>
    <label>Administración de Venta</label>
    <nameField>
        <label>Nombre de Contrato 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Administración de Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato2__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <label>Código AS400/Id. OPAM</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partida de presupuesto</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Contratos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <formula>PartidaPresupuesto__r.Quote.Opportunity.Producto_cotizacion__c</formula>
    <label>Producto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <externalId>true</externalId>
    <label>Codigo AS400</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Contrato_2__c.field-meta.xml
<CustomField>
    <fullName>Contrato_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato2__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IDInterno__c.field-meta.xml
<CustomField>
    <fullName>IDInterno__c</fullName>
    <externalId>true</externalId>
    <label>ID Interno</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SIGLO_Transaccional_FieldMapping.cls
public class SIGLO_Transaccional_FieldMapping {

    public static Map<String, String> createJSON(List<ContratoFilial__c> scope, Boolean encrypted){
        Map<String, String> productsJSON = new Map<String, String>();
        String responseJSON, clientesJSON, productId;
        for(ContratoFilial__c cf : scope){
            productId = cf.Producto__r.IDInterno__c;
            //responseJSON = encrypted ? fillJSON_Encrypted(opp, quote) : fillJSON(opp, quote);
            responseJSON = fillJSON(cf, encrypted);
            if(productsJSON.containsKey(productId+'-transacciones')){
                clientesJSON = productsJSON.get(productId+'-transacciones');
                productsJSON.put(productId+'-transacciones', clientesJSON + ',' + responseJSON);
            }else{
                productsJSON.put(productId+'-transacciones', responseJSON);
            }
            //clientesJSON = clientesJSON != null ? clientesJSON + ',' + responseJSON : responseJSON;
        }
        
        //return clientesJSON;
        return productsJSON;
    }

    public static String fillJSON(ContratoFilial__c cf, Boolean encrypted){
        
        SIGLO_Transaccional_JSON clienteJSON = new SIGLO_Transaccional_JSON();

        clienteJSON.ClientCode = cf.Contrato_2__r.CodigoAS400__c != null ? cf.Contrato_2__r.CodigoAS400__c : 'SIN INFORMACION';

        //clienteJSON.Frequency = cf.Contrato_2__r.PartidaPresupuesto__r.Quote.TransactionsEstimatedNumber__c != null ? cf.Contrato_2__r.PartidaPresupuesto__r.Quote.TransactionsEstimatedNumber__c : 3;

        //clienteJSON.Frequency_String = encrypted ? String.valueOf(clienteJSON.Frequency) : '';

        //clienteJSON.Amount = cf.Contrato_2__r.PartidaPresupuesto__r.Quote.TransactionsEstimatedNumber__c != null ? cf.Contrato_2__r.PartidaPresupuesto__r.Quote.TotalPrice : 1000000;

        //clienteJSON.Amount_String = encrypted ? String.valueOF(clienteJSON.Amount) : '';

        if(encrypted){clienteJSON.encryptJSON();}
        //return JSON.serialize(clienteJSON);
        
        return clienteJSON.generateJSONContent(clienteJSON, encrypted);

    }


}