force-app/main/default/objects/Contrato2__c/Contrato2__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite el guardado de los contratos por ADV</description>
    <label>Administración de Venta</label>
    <nameField>
        <label>Nombre de Contrato 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Administración de Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato2__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <label>Código AS400/Id. OPAM</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Administraci_n_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Entidad_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Cuenta</label>
    <referenceTo>EntidadCuenta__c</referenceTo>
    <relationshipName>Administraci_n_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Entidad_Legal__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Legal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Legal</label>
    <referenceTo>EntidadLegal__c</referenceTo>
    <relationshipName>Administraci_n_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partida de presupuesto</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Contratos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/ContratoFilial__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite registrar las filiales en el contrato</description>
    <label>Contrato Filial</label>
    <nameField>
        <label>Código Subcuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos Filial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContratoFilial__c/fields/CodigoAS400__c.field-meta.xml
<CustomField>
    <fullName>CodigoAS400__c</fullName>
    <externalId>true</externalId>
    <label>Codigo AS400</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Contrato_2__c.field-meta.xml
<CustomField>
    <fullName>Contrato_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato2__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/Entidad_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Entidad_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entidad Legal</label>
    <referenceTo>EntidadCuenta__c</referenceTo>
    <relationshipLabel>Contratos Filial</relationshipLabel>
    <relationshipName>Contratos_Filial</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/isPrime__c.field-meta.xml
<CustomField>
    <fullName>isPrime__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContratoFilial__c/fields/NombreEL__c.field-meta.xml
<CustomField>
    <fullName>NombreEL__c</fullName>
    <formula>Entidad_Cuenta__r.EntidadLegal__r.RazonSocial__c</formula>
    <label>NombreEL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PartidaPresupuesto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EC_ListaAS400_Ctrl.cls
/**
	* @author calvarez@ctconsulting.com.mx
	* @date 2018
	* @description Controlador para listar subcuentas AS400.
	* @group EstructuraCuentas
*/
public without sharing class EC_ListaAS400_Ctrl {
	

	/**
		* @author calvarez@ctconsulting.com.mx
		* @date 16/04/2017
		* @param accountId Id de cuenta(Account).
		* @description Obtiene instancias Contrato2__c y ContratoFilial__c asociados a la cuenta.
		* @return Objeto con los resultados obtenidos.
	*/
	@AuraEnabled
	public static Map<String, Object> listaAS400( Id accountId ) {
		Map<String, Object> response = new Map<String, Object>();
		try {
			if ( String.isNotBlank( accountId ) ) {
				if( accountId.getSobjectType() == Schema.Account.SObjectType ) {
					response.put('filiales', [SELECT CodigoAS400__c,Entidad_Cuenta__r.Name,Entidad_Cuenta__c,Id,isPrime__c,Name,NombreEL__c,OwnerId FROM ContratoFilial__c WHERE Entidad_Cuenta__c =: [SELECT id from EntidadCuenta__c where Cuenta__c=:accountId] AND Contrato_2__c=null]);
					response.put('records', [SELECT Id, Cuenta__c, CodigoAS400__c, Entidad_Legal__r.Estatus__c, Entidad_Legal__r.Name, Entidad_Legal__r.RazonSocial__c, Entidad_Legal__r.RecordType.Name, ( SELECT Id, CodigoAS400__c, Entidad_Cuenta__r.NombreEL__c, Entidad_Cuenta__r.RFCEL__c, Entidad_Cuenta__r.Name FROM Contratos_Filial__r WHERE CodigoAS400__c != null AND isPrime__c!=true  ),PartidaPresupuesto__r.Product2.Name , PartidaPresupuesto__r.Product2.ProductCode, PartidaPresupuesto__r.Product2.Family FROM Contrato2__c WHERE Cuenta__c =: accountId AND CodigoAS400__c != null ORDER BY CreatedDate DESC ]);
                    response.put('codigosAs', [SELECT Id,CodigoAS400__c FROM ContratoFilial__c WHERE Entidad_Cuenta__r.Cuenta__c=: accountId]);
				} else {
					throw new PLAN_CuentaService.CustomException('El Id debe ser de tipo Account');
				}
			} else {
				response.put('error', 'Parameter @accountId is required');
			}
		} catch( Exception e ) {
			response.put('exception', e);
		}
		return response;
	}
    
    /**
		* @author sreyna@ctconsulting.com.mx
		* @date 25/04/2017
		* @description Obtiene la URL del tipo de metadato URLAS400 para ser mostrado en pantalla
		* @return String URL
	*/
	@AuraEnabled
	public static String getURL() {
		return [Select URL__c from URLAs400__mdt  Where DeveloperName = 'URLAS400'].URL__c;
	}
}