force-app/main/default/objects/Contrato2__c/Contrato2__c.object-meta.xml
<CustomObject>
    <description>Objeto que permite el guardado de los contratos por ADV</description>
    <label>Administración de Venta</label>
    <nameField>
        <label>Nombre de Contrato 2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Administración de Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato2__c/fields/ComoFactura__c.field-meta.xml
<CustomField>
    <fullName>ComoFactura__c</fullName>
    <label>Cómo Factura</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Empresa</fullName>
            </value>
            <value>
                <fullName>Consolidador</fullName>
            </value>
            <value>
                <fullName>Grupo de Facturación</fullName>
            </value>
            <value>
                <fullName>Grupo de Región</fullName>
            </value>
            <value>
                <fullName>Región</fullName>
            </value>
            <value>
                <fullName>Centro de Costos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/CondicionesPagoPlazo__c.field-meta.xml
<CustomField>
    <fullName>CondicionesPagoPlazo__c</fullName>
    <label>Condiciones de Pago (Plazo)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Controla_Presencia_Vehiculo_NFC__c.field-meta.xml
<CustomField>
    <fullName>Controla_Presencia_Vehiculo_NFC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Controla Presencia Vehículo NFC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/CuotaLitros_Currency__c.field-meta.xml
<CustomField>
    <fullName>CuotaLitros_Currency__c</fullName>
    <label>Cuota por Litros</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/CuotaLitrosLetra_Text__c.field-meta.xml
<CustomField>
    <fullName>CuotaLitrosLetra_Text__c</fullName>
    <label>Cuota por Litros en Letra</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/CuotaMensual_Currency__c.field-meta.xml
<CustomField>
    <fullName>CuotaMensual_Currency__c</fullName>
    <label>Cuota Mensual</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/CuotaMensualLetra_Text__c.field-meta.xml
<CustomField>
    <fullName>CuotaMensualLetra_Text__c</fullName>
    <label>Cuota Mensual en Letra</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/EmpresaPrincipal_PL__c.field-meta.xml
<CustomField>
    <fullName>EmpresaPrincipal_PL__c</fullName>
    <label>Empresa Principal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prime</fullName>
            </value>
            <value>
                <fullName>No Prime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Facturacion_Cargos__c.field-meta.xml
<CustomField>
    <fullName>Facturacion_Cargos__c</fullName>
    <label>Facturación Cargos</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Separado del Consumo</fullName>
            </value>
            <value>
                <fullName>Junto al Consumo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Facturacion_Comision__c.field-meta.xml
<CustomField>
    <fullName>Facturacion_Comision__c</fullName>
    <label>Facturación Comisión</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Separado del Consumo</fullName>
            </value>
            <value>
                <fullName>Junto al Consumo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Facturacion_Plasticos__c.field-meta.xml
<CustomField>
    <fullName>Facturacion_Plasticos__c</fullName>
    <label>Facturación Plásticos</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Separado del Consumo</fullName>
            </value>
            <value>
                <fullName>Junto al Consumo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Item_Contratacion__c.field-meta.xml
<CustomField>
    <fullName>Item_Contratacion__c</fullName>
    <label>Item Contratación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TC Avanzado</fullName>
            </value>
            <value>
                <fullName>TC Basico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/ManejaAutoconsumo_Checkbox__c.field-meta.xml
<CustomField>
    <fullName>ManejaAutoconsumo_Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Maneja Autoconsumo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/ManejaAutoconsumoLetra_Text__c.field-meta.xml
<CustomField>
    <fullName>ManejaAutoconsumoLetra_Text__c</fullName>
    <label>Maneja Autoconsumo en Letra</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Maquila__c.field-meta.xml
<CustomField>
    <fullName>Maquila__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si tiene un maquilador especifico</description>
    <label>Maquila</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/ModoOffline__c.field-meta.xml
<CustomField>
    <fullName>ModoOffline__c</fullName>
    <label>Modo Offline</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cliente NO opera offline</fullName>
            </value>
            <value>
                <fullName>Cliente elige cómo operar</fullName>
            </value>
            <value>
                <fullName>Cliente opera offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partida de presupuesto</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipName>Contratos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Tipo_de_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Facturacion__c</fullName>
    <label>Tipo de Facturación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pedido</fullName>
                <label>Prepago</label>
            </value>
            <value>
                <fullName>Consumo</fullName>
                <label>Pospago</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/Tipo_Maquila__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Maquila__c</fullName>
    <label>Tipo Maquila</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BP Fleet</fullName>
            </value>
            <value>
                <fullName>BP Migrados</fullName>
            </value>
            <value>
                <fullName>Element</fullName>
            </value>
            <value>
                <fullName>G500 FLEET</fullName>
            </value>
            <value>
                <fullName>Hidrosina</fullName>
            </value>
            <value>
                <fullName>Servifacil</fullName>
            </value>
            <value>
                <fullName>Chedraui</fullName>
            </value>
            <value>
                <fullName>Walmart</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/TipoCliente__c.field-meta.xml
<CustomField>
    <fullName>TipoCliente__c</fullName>
    <label>Tipo de Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Facturación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato2__c/fields/TipoPago__c.field-meta.xml
<CustomField>
    <fullName>TipoPago__c</fullName>
    <label>Tipo de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pospago</fullName>
            </value>
            <value>
                <fullName>Prepago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PartidaPresupuesto__c.field-meta.xml
<CustomField>
    <fullName>PartidaPresupuesto__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PartidaPresupuesto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerContrato2.cls
public class TriggerHandlerContrato2 {
    
    public static void metodo(List<Contrato2__c> contratos){
        for(Contrato2__c campo : contratos){
            if(campo.ManejaAutoconsumo_Checkbox__c == TRUE && campo.CuotaMensual_Currency__c != null){
                System.debug('CuotaMensual_Currency__c	 => ' + campo.CuotaMensual_Currency__c);    
                campo.CuotaMensualLetra_Text__c = ConversionNumeroTexto.Convertir(String.Valueof(campo.CuotaMensual_Currency__c), 'moneda');
            }else{
                campo.CuotaMensualLetra_Text__c = 'No Aplica';
            }
            if(campo.ManejaAutoconsumo_Checkbox__c == TRUE && campo.CuotaLitros_Currency__c != null){
                System.debug('CuotaLitros_Currency__c	 => ' + campo.CuotaLitros_Currency__c);    
                campo.CuotaLitrosLetra_Text__c = ConversionNumeroTexto.Convertir(String.Valueof(campo.CuotaLitros_Currency__c), 'moneda');
            }else{
                campo.CuotaLitrosLetra_Text__c = 'No Aplica';
            }
            if(campo.ManejaAutoconsumo_Checkbox__c == TRUE){
                campo.ManejaAutoconsumoLetra_Text__c = 'SI';
            }else{
                campo.ManejaAutoconsumoLetra_Text__c = 'NO';
            }
        }         
    }
    
    public static void asignarValores(List<Contrato2__c> contratosNuevos,Map<Id,Contrato2__c> contratosOld){
        Set<String> listQLI=new Set<String>();
        for(Contrato2__c cont : contratosNuevos){
            listQLI.add(cont.PartidaPresupuesto__c);
        }
        Map<String,String> mapaProductos=new Map<String,String>();
        for(QuoteLineItem qli:[Select Id,Product2.ProductCode from QuoteLineItem where Id IN :listQLI]){
            mapaProductos.put(qli.Id, qli.Product2.ProductCode);
        }
        for(Contrato2__c cont : contratosNuevos){
            if(mapaProductos.containsKey(cont.PartidaPresupuesto__c)&&mapaProductos.get(cont.PartidaPresupuesto__c)=='30-TC4'){
                cont.Item_Contratacion__c='TC Avanzado';
                cont.Controla_Presencia_Vehiculo_NFC__c=true;
            }
            if(trigger.isInsert&&mapaProductos.containsKey(cont.PartidaPresupuesto__c)&&(new List<String>{'30-TC4','30','30-B','30-E','30-G','30-S','31'}.indexOf(mapaProductos.get(cont.PartidaPresupuesto__c))!=-1)){
                Map <String,String> mapMaquila=new Map <String,String>{'30-B'=>'BP Fleet','30-E'=>'Element','30-G'=>'G500 FLEET','30-S'=>'Servifacil'};
                if(mapaProductos.get(cont.PartidaPresupuesto__c)=='31'){
                    cont.Item_Contratacion__c='TC Avanzado';
                    cont.Facturacion_Comision__c='Separado del Consumo';
                    cont.ComoFactura__c='Empresa';
                    cont.EmpresaPrincipal_PL__c='Prime';
                    cont.ModoOffline__c='Cliente NO opera offline';
                }else{
                    cont.Facturacion_Cargos__c='Separado del Consumo';
                }
                if(new List<String>{'30-B','30-E','30-G','30-S'}.indexOf(mapaProductos.get(cont.PartidaPresupuesto__c))!=-1&&mapMaquila.containsKey(mapaProductos.get(cont.PartidaPresupuesto__c))){
                    cont.Maquila__c=true;
                    cont.Tipo_Maquila__c=mapMaquila.get(mapaProductos.get(cont.PartidaPresupuesto__c));
                }
                
                cont.Facturacion_Plasticos__c='Separado del Consumo';
            }
            if(Trigger.isUpdate&&cont.TipoPago__c!=contratosOld.get(cont.Id).TipoPago__c&&mapaProductos.containsKey(cont.PartidaPresupuesto__c)&&(new List<String>{'30-TC4','30','30-B','30-E','30-G','30-S'}.indexOf(mapaProductos.get(cont.PartidaPresupuesto__c))!=-1)){
                if(cont.TipoPago__c=='Prepago'){
                    //cont.CondicionesPagoPlazo__c='0';
                    cont.Tipo_de_Facturacion__c='Pedido';
                }else{
                    cont.Tipo_de_Facturacion__c='Consumo';
                }
            }
            /*if(Trigger.isUpdate&&cont.ComoFactura__c!=contratosOld.get(cont.Id).ComoFactura__c&&mapaProductos.containsKey(cont.PartidaPresupuesto__c)&&mapaProductos.get(cont.PartidaPresupuesto__c)=='30-TC4'||mapaProductos.containsKey(cont.PartidaPresupuesto__c)&&mapaProductos.get(cont.PartidaPresupuesto__c)=='30'){
                if(cont.ComoFactura__c=='Consolidador'){
                    cont.TipoCliente__c='Web';
                }else{
                    cont.TipoCliente__c='Facturación';
                }
            } */
            if(Trigger.isUpdate&&cont.TipoPago__c!=contratosOld.get(cont.Id).TipoPago__c&&mapaProductos.containsKey(cont.PartidaPresupuesto__c)&&(new List<String>{'31'}.indexOf(mapaProductos.get(cont.PartidaPresupuesto__c))!=-1)){
                if(cont.TipoPago__c == 'Prepago' && cont.Facturacion_Cargos_Prepago__c != null){
                    cont.Facturacion_Cargos__c='Separado del Consumo';
                }
            }
        }
    }
}